# Helper function for importing counts generated by featureCounts (subread package)
getRawCounts <- function(folder){ 
	samples <- clintable$sample

	countData <- NULL
	for(i in 1:length(samples)){
	  if(i < 2){
		countData <- as.matrix(read.csv(file = paste0(folder,samples[i],".fc"), 
										header = F, sep = "\t", 
										row.names=1,
										check.names = F,
										comment.char = "#"))
	  }
	  else{
		countData <- cbind(countData,read.csv(file = paste0(folder,samples[i],".fc"),
											  header = F,
											  sep = "\t",
											  check.names = F,
											  comment.char = "#")[,2])
	  }
	}
	colnames(countData) <- c(samples)
	return(countData)
}

# Generate TPM values for counttable 'c' using list of gene lengths 'gl'
getTPMtable <- function(c,gl){
  gl <- gl[match(rownames(c),gl$geneID),]
  gl$length <- gl$length/1000
  rpk <- sweep(c,MARGIN=1,gl$length,'/')
  totalrpk <- colSums(rpk)
  totalrpk <- totalrpk/1000000
  tpm <- sweep(rpk,MARGIN=2,totalrpk,'/')
  return(tpm)
}
isEmpty <- function(x) {
    return(length(x)==0)
}